---
name: ci repo CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python-checks:
    strategy:
      matrix:
        include:
          # MANDATORY CHECKS USING CURRENT DEVELOPMENT INTERPRETER
          - dependencies: >
              pylint
              python3-dbus
              python3-dbus-python-client-gen
              python3-matplotlib
              python3-numpy
              python3-pygithub
              python3-requests
              python3-semantic_version
            task: lint
          - dependencies: >
              black
              python3-isort
              shfmt
            task: fmt-travis
          - dependencies: >
              yamllint
            task: yamllint
          - dependencies: >
              findutils
              ShellCheck
            task: shellcheck
    runs-on: ubuntu-18.04
    container: fedora:34  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: Run test
        run: make -f Makefile ${{ matrix.task }}
