---
name: ci repo nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 35 3 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # PYTHON CHECKS ON NEXT FEDORA PYTHON AND PYTHON TOOLS VERSION
          - dependencies: >
              pylint
              python3-pygithub
              python3-requests
              python3-semantic_version
            image: fedora:34
            task: lint
          - dependencies: >
              black
              python3-isort
            image: fedora:34
            task: fmt-travis

    runs-on: ubuntu-18.04
    container: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          python-unversioned-command
          ${{ matrix.dependencies }}
      - name: Run test
        run: make -f Makefile ${{ matrix.task }}
