---
name: ci repo weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 35 3 * * 5
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # PYTHON CHECKS ON NEXT FEDORA PYTHON AND PYTHON TOOLS VERSION
          - dependencies: >
              pylint
              python3-dbus
              python3-dbus-python-client-gen
              python3-pygithub
              python3-requests
              python3-semantic_version
            task: lint
          - dependencies: >
              black
              python3-isort
              shfmt
            task: fmt-travis
          - dependencies: yamllint
            task: yamllint

    runs-on: ubuntu-18.04
    container: fedora:34
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: make -f Makefile ${{ matrix.task }}
        run: make -f Makefile ${{ matrix.task }}
